### ISSUE TITLE
Slower with version 3.x

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/vite#11]
### Package version

3.0.0-8

### Describe the bug

Hello,

Since the version 3.x, I'm seeing that the server startup is significantly slower.

I'm on WSL and I also try on MacOS Intel and I've got the same result.

_Project is the same, the only diff is the version of the adonisjs vite package (and related configuration)_

Fresh Adonis Web starter with adonisjs/vite 2.x

![image](https://github.com/adonisjs/vite/assets/45267552/07eb220f-d338-4272-ab87-eb11329e1a5e)

![image](https://github.com/adonisjs/vite/assets/45267552/0e1a5ea1-e465-4d6b-b3d3-449ef4195f7c)

Fresh Adonis Web start with adonisjs/vite 3.x

![image](https://github.com/adonisjs/vite/assets/45267552/155782e1-598b-46d0-a727-e077d7d6a4d4)

![image](https://github.com/adonisjs/vite/assets/45267552/37e6f1e6-3646-41d7-8059-ba859b47a314)

![image](https://github.com/adonisjs/vite/assets/45267552/6357ec4e-0beb-40fd-aa8d-ff1b8076fd0f)

**Comment by Julien-R44** [comment]
did you add `assetsBundler: false` in your `.adonisrc.ts` file?

**Comment by Barbapapazes** [comment]
yes! (see https://github.com/Barbapapazes/adonis-vite-fouc for the reproduction)

**Comment by Julien-R44** [comment]
Maybe it will be better with this commit https://github.com/adonisjs/vite/commit/76016e41e05e470e7da55f1cb94c5937342ed9cb

But i am not totally convinced. Let's see with the next release

**Comment by Julien-R44** [comment]
Published. Let me know if you notice any difference : https://github.com/adonisjs/vite/releases/tag/v3.0.0-9

if no major difference : i still have an idea in mind that I will start working on

**Comment by Barbapapazes** [comment]
MacBook Pro 2017, Node 18.19, adonis/vite 3.0.0-8

<img width="512" alt="image" src="https://github.com/adonisjs/vite/assets/45267552/6067ec4e-afda-42ac-b7b1-fdc87f329c2d">

MacBook Pro 2017, Node 18.19, adonis/vite 3.0.0-9

<img width="512" alt="image" src="https://github.com/adonisjs/vite/assets/45267552/ab1c85c0-c5b0-42f1-ae08-c352d5b1d3a3">

MacBook Pro 2017, Node 20.11, adonis/vite 3.0.0-9

<img width="512" alt="image" src="https://github.com/adonisjs/vite/assets/45267552/cbf4cfe9-dd71-442d-938f-c7830ba7794d">

**Comment by Barbapapazes** [comment]
Not a lot of change

**Comment by thetutlage** [comment]
Yeah, seems like it has to do with Vite running in the same process as the AdonisJS app. Whereas, earlier it was a different process.

Wild idea - Can't we run Vite inside a worker thread and still use some sort of API to achieve SSR?

**Comment by Julien-R44** [comment]
Maybe, i am not sure, but at least I am sure it would require a lot of work

For example, to avoid FOUC in dev, we have to explore the module graph that is exposed by the Vite dev server: https://github.com/adonisjs/vite/blob/next/src/vite.ts#L234

To achieve that with worker threads, we would need to make a whole new API to allow this data to be communicated through `postMessage` between the worker thread hosting Vite and the Adonis process. And this is just a single example, but we probably have to do this for every Vite methods that we could need

**Comment by Julien-R44** [comment]
BTW, I also explored the idea of starting the Vite server in the middleware rather than in the provider (i.e. at boot time).

The result is not very satisfying: 

So yeah, it does start up faster, and the Vite startup time is postponed to the first request. 
But having said that, it poses another problem on Inertia or TSX applications: the page is no longer refreshed automatically. 

Because it works like this actually :

- We render the /home page on our browser. This same /home page is injected with the `@vite/client` script, which instantiates a websocket channel for HMR.
- As soon as you modify the codebase, the entire Adonis process is restarted, which CUTs off the websocket connection.
- Our browser, still on the /home page, tries to reconnect to the websocket. Once the websocket connection is re-established, Vite automatically refreshes the page.

If we start Vite in the middleware, this doesn't work anymore. the browser will constantly try to reconnect, but will not be able to do so until the Vite dev server is recreated. So until the first request is made.

So yeah I don't think it's the solution either.

---

I think we're left with two things:

- HMR. I think it's very promising
- Or a solution with worker threads, or even going back to a second child process, but with a way of communicating with it. This library is interesting : https://github.com/antfu/birpc

**Comment by thetutlage** [comment]
> If we start Vite in the middleware, this doesn't work anymore. the browser will constantly try to reconnect, but will not be able to do so until the Vite dev server is recreated. So until the first request is made.

But wouldn't this be the case even if we start Vite dev server in the provider and without HMR enabled?

---

> HMR. I think it's very promising

Yeah, it seems like HMR is the only way to achieve the desired DX, otherwise regardless of the slow startup, the disconnection of WS connection is problematic as well.

**Comment by Julien-R44** [comment]
> But wouldn't this be the case even if we start Vite dev server in the provider and without HMR enabled?

Not sure what you mean here. Today, with our current implementation, the Vite dev server is started in the provider, and the page's autorefresh works fine, thanks to `@vite/client` HMR. But yeah, if we disable Vite's HMR in `vite.config`, it will not work anymore. But why would we disable Vite's HMR?

**Comment by Julien-R44** [comment]
Given that [we've released HMR](https://adonisjs.com/blog/hmr-in-adonisjs), I don't think the problem is really relevant anymore, as we don't need to full restart the server so often

If it turns out to still be a problem, we'll re-open the issue and maybe try to implement a solution with worker threads/rpc as mentioned above
