### ISSUE TITLE
Does not works well with TSX

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/vite#8]
### Package version

v3.0.0-8

### Describe the bug

Hello,

I'm using the latest version of the Vite plugin with the setup indicated in this blog article: https://adonisjs.com/blog/use-tsx-for-your-template-engine.

Every time I save a `tsx` file in the resource directory, even with the `reloadServer` set to false, the server reload. With `edge`, only the page reload. Is this the expected behavior ? Also, I setup `css` file in the TS file but this create a fouc because assets take more than 2 seconds to loads (and loads after the JS loads).

**Comment by Barbapapazes** [comment]
With a very simple app (the web start), moving from v2 to v3 increase start up time from 500ms to 2s which is a lot.

**Comment by Julien-R44** [comment]
there are several mixed issues in this thread. it would be nice to open separate issues afterwards

> Every time I save a tsx file in the resource directory, even with the reloadServer set to false, the server reload. With edge, only the page reload. Is this the expected behavior

Yes. Long story short : a TSX file is a javascript file that is imported via an `import`. Javascript maintains a cache of imported files. If you import the same file twice, you'll get the same content. So, if you want to have the latest version of `home.tsx`, you need to restart the node process. 

We need to experiment with ESM cache busting solutions for this. But for now, yes, that's the expected behavior. In any case, there's no relation with adonisjs/vite here

> Also, I setup css file in the TS file but this create a fouc because assets take more than 2 seconds to loads (and loads after the JS loads).

What do you use to make your CSS? Tailwind, SASS, vanilla CSS ? Usually the solution is just to create a specific entrypoint for your CSS and load it separately like `@vite(['resources/js/app.js, 'resources/css/app.css'])`.

If you're using something like UnoCSS, with which you have to import CSS via Javascript, then yes you'll have a FOUC. This problem has been solved on adonisjs/inertia, but I'll have to look into backporting a solution into adonisjs/vite.

> With a very simple app (the web start), moving from v2 to v3 increase start up time from 500ms to 2s which is a lot.

OS ? Windows ?

**Comment by Barbapapazes** [comment]
Thanks for this answer! I will open decated issues with more details!

**Comment by Julien-R44** [comment]
Thank for splitting the issues. i think we can close this one
